name: Sayanee
description: on web & iot, minimalism, space
destination: ./_publish
permalink: /:title
markdown: redcarpet
url: http://sayanee.github.io/blog

exclude: ['sass', 'node_modules', 'Gruntfile.js', 'package.json', 'readme.md']
