name: Sayanee
description: on web and iot, minimalism, space
destination: ./_publish
permalink: /:title
markdown: redcarpet
url: http://blog.sayan.ee

exclude: ['sass', 'node_modules', 'Gruntfile.js', 'package.json', 'readme.md']
